version: '3.7'

services:
  elasticsearch:
    image: elastic/elasticsearch:8.11.1
    container_name: backend-python-tochka-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: elastic/kibana:8.11.1
    container_name: backend-python-tochka-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-python-tochka
    ports:
      - "9003:8000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - .:/app
    command: ["./scripts/start_with_migration.sh"]

volumes:
  esdata:
