"""add blocked_amount to balance

Revision ID: 1f285bdfaf65
Revises: ae663042214b
Create Date: 2025-05-15 20:02:34.924199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f285bdfaf65'
down_revision: Union[str, None] = 'ae663042214b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('blocked_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance', 'blocked_amount')
    # ### end Alembic commands ###
