"""Add_instruments_and_its_management

Revision ID: 65ca00232308
Revises: a8a53aa419ce
Create Date: 2025-04-22 23:23:25.436973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ca00232308'
down_revision: Union[str, None] = 'a8a53aa419ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'instrument',
        sa.Column('ticker', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument')),
    )
    op.create_index(op.f('ix_instrument_ticker'), 'instrument', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrument_ticker'), table_name='instrument')
    op.drop_table('instrument')
    # ### end Alembic commands ###
