"""add balance

Revision ID: 002fbd1d4e22
Revises: a8a53aa419ce
Create Date: 2025-04-09 21:20:45.003070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002fbd1d4e22'
down_revision: Union[str, None] = 'a8a53aa419ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'balance',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('ticker', sa.String(length=10), nullable=False),
        sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
        sa.CheckConstraint('amount >= 0', name=op.f('ck_balance_positive_balance')),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('fk_balance_user_id_user')
        ),
        sa.PrimaryKeyConstraint('user_id', 'ticker', name=op.f('pk_balance')),
    )
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('balance', sa.NUMERIC(), autoincrement=False, nullable=False)
    )
    op.drop_table('balance')
    # ### end Alembic commands ###
