"""add transaction

Revision ID: ae60731d6fc6
Revises: 85342a739688
Create Date: 2025-05-15 15:53:58.776505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae60731d6fc6'
down_revision: Union[str, None] = '85342a739688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_balance_ticker_instrument', 'balance', type_='foreignkey')
    op.create_foreign_key(
        op.f('fk_balance_ticker_instrument'),
        'balance',
        'instrument',
        ['ticker'],
        ['ticker'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        op.f('fk_order_user_id_user'),
        'order',
        'user',
        ['user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_user_id_user'), 'order', type_='foreignkey')
    op.drop_constraint(
        op.f('fk_balance_ticker_instrument'), 'balance', type_='foreignkey'
    )
    op.create_foreign_key(
        'fk_balance_ticker_instrument', 'balance', 'instrument', ['ticker'], ['ticker']
    )
    # ### end Alembic commands ###
