"""ticker in transaction

Revision ID: 7b9452683a82
Revises: 26a9773165dc
Create Date: 2025-05-17 05:31:22.584215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9452683a82'
down_revision: Union[str, None] = '26a9773165dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f('fk_transaction_ticker_instrument'),
        'transaction',
        'instrument',
        ['ticker'],
        ['ticker'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_transaction_ticker_instrument'), 'transaction', type_='foreignkey'
    )
    # ### end Alembic commands ###
