"""amount integer

Revision ID: 30a40ff621d1
Revises: ecc69bb4e6a9
Create Date: 2025-05-12 19:23:20.397498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a40ff621d1'
down_revision: Union[str, None] = 'ecc69bb4e6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'balance',
        'amount',
        existing_type=sa.NUMERIC(precision=20, scale=10),
        type_=sa.Integer(),
        nullable=False,
    )
    op.create_unique_constraint(op.f('uq_instrument_ticker'), 'instrument', ['ticker'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_instrument_ticker'), 'instrument', type_='unique')
    op.alter_column(
        'balance',
        'amount',
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=20, scale=10),
        nullable=True,
    )
    # ### end Alembic commands ###
