"""add order

Revision ID: 85342a739688
Revises: 30a40ff621d1
Create Date: 2025-05-12 20:02:30.176878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85342a739688'
down_revision: Union[str, None] = '30a40ff621d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'NEW', 'EXECUTED', 'PARTIALLY_EXECUTED', 'CANCELLED', name='orderstatus'
            ),
            nullable=False,
        ),
        sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            'direction', sa.Enum('BUY', 'SELL', name='orderdirection'), nullable=False
        ),
        sa.Column('ticker', sa.String(), nullable=False),
        sa.Column('qty', sa.Integer(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=True),
        sa.Column('filled', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['ticker'],
            ['instrument.ticker'],
            name=op.f('fk_order_ticker_instrument'),
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_order')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
