"""new migration

Revision ID: ecc69bb4e6a9
Revises: 
Create Date: 2025-05-12 19:11:26.230793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc69bb4e6a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'instrument',
        sa.Column('ticker', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('ticker', name=op.f('pk_instrument')),
        sa.UniqueConstraint('ticker', name=op.f('uq_instrument_ticker')),
    )
    op.create_table(
        'user',
        sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
        sa.UniqueConstraint('api_key', name=op.f('uq_user_api_key')),
        sa.UniqueConstraint('id', name=op.f('uq_user_id')),
    )
    op.create_table(
        'balance',
        sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('ticker', sa.String(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=True),
        sa.CheckConstraint('amount >= 0', name=op.f('ck_balance_positive_balance')),
        sa.ForeignKeyConstraint(
            ['ticker'], ['instrument.ticker'], name=op.f('fk_balance_ticker_instrument')
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('fk_balance_user_id_user')
        ),
        sa.PrimaryKeyConstraint('user_id', 'ticker', name=op.f('pk_balance')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance')
    op.drop_table('user')
    op.drop_table('instrument')
    # ### end Alembic commands ###
