"""cascade for instrument in order

Revision ID: 15a4d1c863b7
Revises: 1f285bdfaf65
Create Date: 2025-05-15 22:36:52.709474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a4d1c863b7'
down_revision: Union[str, None] = '1f285bdfaf65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'balance', 'blocked_amount', existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint('fk_order_ticker_instrument', 'order', type_='foreignkey')
    op.create_foreign_key(
        op.f('fk_order_ticker_instrument'),
        'order',
        'instrument',
        ['ticker'],
        ['ticker'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_ticker_instrument'), 'order', type_='foreignkey')
    op.create_foreign_key(
        'fk_order_ticker_instrument',
        'order',
        'instrument',
        ['ticker'],
        ['ticker'],
        ondelete='RESTRICT',
    )
    op.alter_column(
        'balance', 'blocked_amount', existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
