"""Add instruments and its management

Revision ID: 676dc54070f3
Revises: a8a53aa419ce
Create Date: 2025-04-09 20:43:17.242516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676dc54070f3'
down_revision: Union[str, None] = 'a8a53aa419ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'instrument',
        sa.Column('ticker', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument')),
        sa.UniqueConstraint('ticker', name=op.f('uq_instrument_ticker')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument')
    # ### end Alembic commands ###
